import type { Field } from "payload";

export const seoFields = (): Field => ({
  name: "seo",
  type: "group",
  label: "SEO",
  fields: [
    { name: "title", type: "text", label: "SEO-заголовок", maxLength: 180 },
    { name: "description", type: "textarea", label: "SEO-описание", maxLength: 320 },
    { name: "canonical", type: "text", label: "Канонический URL" },
    { name: "noIndex", type: "checkbox", label: "Не индексировать" },
    { name: "ogImage", type: "upload", relationTo: "media", label: "OG-изображение" },
  ],
});

export const conditionField = (name = "condition"): Field => ({
  name,
  type: "json",
  label: "Условие",
  admin: {
    description:
      'AST без кода: operator equals/notEquals/in/notIn/contains/exists/greaterThan/lessThan/and/or/not. Пример: {"operator":"equals","field":"country","value":"KZ"}.',
    maxHeight: 280,
  },
});

const operandFields = (prefix: string, label: string): Field => ({
  name: prefix,
  type: "group",
  label,
  fields: [
    {
      name: "source",
      type: "select",
      label: "Источник",
      defaultValue: "field",
      options: [
        { label: "Поле формы", value: "field" },
        { label: "Константа", value: "constant" },
        { label: "Другая формула", value: "formula" },
      ],
    },
    { name: "field", type: "text", label: "Ключ поля" },
    { name: "value", type: "text", label: "Значение" },
    { name: "formula", type: "text", label: "Ключ формулы" },
  ],
});

export const toolDefinitionFields = (): Field[] => [
  {
    name: "fields",
    type: "array",
    label: "Поля формы",
    admin: { description: "Какие данные спрашивать у пользователя. Ключи используются в правилах и формулах." },
    fields: [
      { name: "key", type: "text", label: "Ключ", required: true },
      { name: "label", type: "text", label: "Подпись", required: true },
      {
        name: "type",
        type: "select",
        label: "Тип поля",
        required: true,
        options: [
          { label: "Текст", value: "text" },
          { label: "Многострочный текст", value: "textarea" },
          { label: "Число", value: "number" },
          { label: "Деньги", value: "currency" },
          { label: "Дата", value: "date" },
          { label: "Диапазон дат", value: "dateRange" },
          { label: "Список", value: "select" },
          { label: "Переключатели", value: "radio" },
          { label: "Да/нет", value: "checkbox" },
          { label: "Несколько значений", value: "multiSelect" },
        ],
      },
      { name: "required", type: "checkbox", label: "Обязательное" },
      { name: "placeholder", type: "text", label: "Подсказка в поле" },
      { name: "helpText", type: "textarea", label: "Пояснение" },
      { name: "min", type: "number", label: "Минимум" },
      { name: "max", type: "number", label: "Максимум" },
      { name: "step", type: "number", label: "Шаг" },
      { name: "defaultValue", type: "text", label: "Значение по умолчанию" },
      {
        name: "options",
        type: "array",
        label: "Варианты",
        fields: [
          { name: "value", type: "text", label: "Значение", required: true },
          { name: "label", type: "text", label: "Подпись", required: true },
          { name: "description", type: "textarea", label: "Описание" },
        ],
      },
    ],
  },
  {
    name: "formulas",
    type: "array",
    label: "Формулы",
    admin: { description: "Формулы выполняются безопасным интерпретатором, без JavaScript и eval." },
    fields: [
      { name: "key", type: "text", label: "Ключ результата", required: true },
      { name: "label", type: "text", label: "Подпись результата" },
      {
        name: "kind",
        type: "select",
        label: "Операция",
        required: true,
        options: [
          { label: "Сложение", value: "add" },
          { label: "Вычитание", value: "subtract" },
          { label: "Умножение", value: "multiply" },
          { label: "Деление", value: "divide" },
          { label: "Процент", value: "percent" },
          { label: "Округление", value: "round" },
          { label: "Минимум", value: "min" },
          { label: "Максимум", value: "max" },
          { label: "Разница дат", value: "dateDiffDays" },
          { label: "Прибавить дни", value: "dateAddDays" },
          { label: "Поиск в таблице", value: "lookup" },
          { label: "Условное значение", value: "conditional" },
          { label: "Нормализовать число", value: "normalizeNumber" },
        ],
      },
      operandFields("left", "Левый операнд"),
      operandFields("right", "Правый операнд"),
      {
        name: "operands",
        type: "array",
        label: "Операнды для min/max",
        fields: [
          { name: "source", type: "select", options: ["field", "constant", "formula"], label: "Источник" },
          { name: "field", type: "text", label: "Ключ поля" },
          { name: "value", type: "text", label: "Значение" },
          { name: "formula", type: "text", label: "Ключ формулы" },
        ],
      },
      { name: "digits", type: "number", label: "Знаков после запятой", min: 0, max: 8 },
      operandFields("days", "Количество дней"),
      conditionField(),
      operandFields("thenValue", "Если условие истинно"),
      operandFields("elseValue", "Если условие ложно"),
      { name: "tableKey", type: "text", label: "Ключ таблицы" },
      { name: "lookupField", type: "text", label: "Колонка поиска" },
      operandFields("lookupValue", "Искомое значение"),
      { name: "resultField", type: "text", label: "Колонка результата" },
    ],
  },
  {
    name: "steps",
    type: "array",
    label: "Шаги сценария",
    fields: [
      { name: "stepId", type: "text", label: "Ключ шага", required: true, admin: { description: "Уникальный ключ внутри этого сценария. Используйте его в полях «Следующий шаг» и «Куда перейти»." } },
      {
        name: "type",
        type: "select",
        label: "Тип шага",
        required: true,
        options: ["question", "info", "branch", "calculation", "checklist", "result", "cta"],
      },
      { name: "title", type: "text", label: "Заголовок", required: true },
      { name: "body", type: "textarea", label: "Текст" },
      { name: "fieldKey", type: "text", label: "Ключ поля вопроса" },
      { name: "required", type: "checkbox", label: "Ответ обязателен" },
      {
        name: "options",
        type: "array",
        label: "Варианты ответа",
        fields: [
          { name: "value", type: "text", label: "Значение", required: true },
          { name: "label", type: "text", label: "Подпись", required: true },
          { name: "description", type: "textarea", label: "Описание" },
        ],
      },
      { name: "formulaKey", type: "text", label: "Ключ формулы" },
      { name: "resultKey", type: "text", label: "Ключ результата" },
      { name: "nextStepId", type: "text", label: "Следующий шаг" },
      {
        name: "branches",
        type: "array",
        label: "Ветвления",
        fields: [conditionField(), { name: "nextStepId", type: "text", label: "Куда перейти", required: true }],
      },
      {
        name: "checklistItems",
        type: "array",
        label: "Пункты чек-листа",
        fields: [
          { name: "key", type: "text", label: "Ключ", required: true },
          { name: "label", type: "text", label: "Пункт", required: true },
          { name: "description", type: "textarea", label: "Пояснение" },
          { name: "group", type: "text", label: "Группа" },
          conditionField(),
        ],
      },
    ],
  },
  {
    name: "results",
    type: "array",
    label: "Результаты",
    fields: [
      { name: "key", type: "text", label: "Ключ", required: true },
      {
        name: "status",
        type: "select",
        label: "Статус",
        options: ["success", "warning", "error", "info"],
        defaultValue: "info",
      },
      { name: "title", type: "text", label: "Заголовок", required: true },
      { name: "body", type: "textarea", label: "Текст результата" },
      conditionField(),
      {
        name: "links",
        type: "array",
        label: "Ссылки",
        fields: [
          { name: "href", type: "text", label: "Ссылка", required: true },
          { name: "label", type: "text", label: "Подпись", required: true },
        ],
      },
      { name: "ctaLabel", type: "text", label: "Текст CTA" },
      { name: "ctaHref", type: "text", label: "Ссылка CTA" },
    ],
  },
  {
    name: "uiCopy",
    type: "group",
    label: "Тексты интерфейса",
    fields: [
      { name: "startLabel", type: "text", label: "Начать" },
      { name: "nextLabel", type: "text", label: "Дальше" },
      { name: "backLabel", type: "text", label: "Назад" },
      { name: "resetLabel", type: "text", label: "Начать заново" },
      { name: "calculateLabel", type: "text", label: "Рассчитать" },
      { name: "resultLabel", type: "text", label: "Результат" },
      { name: "loadingLabel", type: "text", label: "Загрузка" },
      { name: "errorLabel", type: "text", label: "Ошибка" },
      { name: "emptyLabel", type: "text", label: "Нет результата" },
      { name: "requiredLabel", type: "text", label: "Обязательное поле" },
    ],
  },
  {
    name: "integration",
    type: "group",
    label: "Интеграция",
    fields: [
      { name: "providerKey", type: "text", label: "Ключ адаптера" },
      { name: "requestMapping", type: "json", label: "Маппинг запроса", admin: { description: "JSON вида { \"apiField\": \"fieldKey\" }; добавляет адаптеру поля из ответов формы.", maxHeight: 180 } },
      { name: "responseMapping", type: "json", label: "Маппинг ответа", admin: { description: "JSON вида { \"result.body\": \"result.title\", \"externalStatus\": \"result.status\" }; переносит нормализованный ответ в результат или values.", maxHeight: 180 } },
      { name: "timeoutMs", type: "number", label: "Таймаут (мс)", min: 100, max: 30000, defaultValue: 10000 },
      { name: "enabled", type: "checkbox", label: "Включить" },
    ],
  },
  {
    name: "ai",
    type: "group",
    label: "Настройки AI",
    fields: [
      { name: "systemPrompt", type: "textarea", label: "Системная инструкция" },
      { name: "tone", type: "text", label: "Тон ответа" },
      { name: "answerFormat", type: "textarea", label: "Формат ответа" },
      { name: "sourceFilters", type: "text", hasMany: true, label: "Фильтры источников" },
      { name: "maxSources", type: "number", label: "Максимум источников", min: 1, max: 20 },
      { name: "maxTokens", type: "number", label: "Максимум токенов", min: 100, max: 8000 },
    ],
  },
];
